name: airwatch_app
description: Air Quality Tracker

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^4.0.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.0
 
  airquality_repository:
    path: packages/airquality_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^0.3.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/.env